# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Fenchurch::Syncotron::Site"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

# For session support enable the following line and see Dancer::Session
# session: "YAML"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

serializer: "JSON"

plugins:
  Database:
    driver: 'mysql'
    host: 'localhost'
    port: 3306
    database: 'test_adhocument'
    username: 'root'
    password: ''
    connection_check_threshold: 10
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
    on_connect_do:
      - "SET SQL_MODE='TRADITIONAL'"
    log_queries: 1
    connections:
      sphinx:
        driver: 'mysql'
        host: '127.0.0.1'
        port: 9306

engines:
  JSON:
    pretty: 0
